#!/bin/bash

# arithmetic expension(算術式展開): $(( expression )), 整数のみ対応、小数を含んだ計算はbc(basic calculation)を使用
x=4
y=2
echo $(( $x + $y ))
echo $(( x + y ))
echo $(( x - y ))
echo $(( x / y ))
echo $(( x * y ))
echo $(( 2 + 3 * 4 ))
echo $(( (2 + 3) * 4 ))
echo $(( 4 ** 2 ))
echo $(( 4 % 2 ))
echo $(( 5 % 3 ))
echo $(( 2.5 + 1 )) # invalid arithmetic operator
echo $(( 5 / 2 )) # 2
# basic calculation
# "scale=number; expression" | bc => scaleを省略すると小数点0桁表示
echo "5/2" | bc # 2, scaleを省略すると0扱い
echo "scale=2; 5/2" | bc # 2.50, scaleで小数点指定、expression; scale=numberは不可
echo "scale=10; 5/2" | bc # 2.5000000000
# べき乗はbcでは^を使用, **は不可
echo "2 ** 10" | bc # bad expression
echo "2 ^ 10" | bc
# tilda expansion(チルダ展開)
echo ~ # $HOME
echo ~root # /root, root userが有効なuserであるときそのhome dirctoryを返す
echo ~abcd # ~abcd, 有効なuser出ない時は文字列として処理
echo $PWD # shell variable, current dir
echo $OLDPWD # 1つ前のdir
echo ~+ # $PWD
echo ~- # $OLDPWD
# brace expansion(ブレース展開)
# string list, {}の中にspaceを入れると機能しないので注意
echo {a,19,z,barry,42} # a 19 z barry 42
echo {jan,feb,mar,apr,may,jun} # jan feb mar apr may jun
# fail
echo {jan,feb,mar,apr,may, jun} # {jan,feb,mar,apr,may, jun}
echo { jan,feb,mar,apr,may,jun} # { jan,feb,mar,apr,may,jun}
# range list
echo {1,2,3,4,5,6,7,8,9,10} # 1 2 3 4 5 6 7 8 9 10
echo {1..10} # 1 2 3 4 5 6 7 8 9 10
echo {10..1} # 10 9 8 7 6 5 4 3 2 1
echo {a..z} # a b c d e f g h i j k l m n o p q r s t u v w x y z
echo {1..1000..3} # {start..end..step}
# fail
echo {1..q} # {1..q}
echo {jan..dec} # {jan..dec}
# journal folder以下に月folder/日付file作成
echo month{1..12}
echo month{01..12} # mkdir month{01..12}
echo month{01..12}/day{01..31}.txt # touch month{01..12}/day{01..31}.txt