#!/bin/bash

# Author: tatsurodev
# Date Created: 06/07/2023
# Last Modified: 06/07/2023

# Description:
# Creates a backup in ~/bash_course folder of all files in the home directory

# Usage:
# backup_script

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0
